# .github/workflows/sync_public.yml
name: Sync to PyExtal Repository

on:
  push:
    branches:
      - main # Or whatever your default branch is
  
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Private Repo
        uses: actions/checkout@v4
        with:
          # Fetch all history and tags
          fetch-depth: 0

      - name: Set up git identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Remove Proprietary Code
        run: |
          # Use git rm to remove the folder from the repository's history on this checkout
          # The --ignore-unmatch flag prevents errors if the file doesn't exist
          git rm -r --cached --ignore-unmatch makefile
          # You can add more rm lines for other files/folders

          # Commit the removal. This commit is temporary for the push.
          git commit -m "CI: Remove proprietary source for public sync"

      - name: Push to Public Repository
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TEST_TEST_TOKEN }}
          repository: swampni/test_test
          branch: main # The branch to push to in the public repo
          force: true # Force push to overwrite the public repo's history
          tags: true  # Also push tags
